name: Cross-Platform Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up CMake
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y cmake build-essential libglfw3-dev libfreetype6-dev

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install cmake glfw freetype

      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      # Configure the build
      - name: Configure with CMake
        run: cmake -B build -G "Unix Makefiles"
        shell: bash

      # Build the project
      - name: Build the project
        run: cmake --build build --config Release

      # Run tests (if applicable)
      - name: Run tests
        if: always()
        run: |
          cd build && ctest
        shell: bash
